### ISSUE TITLE
missing lines in output | blinking cursor

### ISSUE THREAD

**Issue by iefdev** [alewmoose/2048-in-terminal#2]
They've appearently made a lot of changes to xterm in ncurses (6.1) [»»][nc], so when installing now, there are missing vertical lines in the output.

![2048](https://user-images.githubusercontent.com/3958664/52407854-ad90f300-2ad1-11e9-93b7-2becb50db4ae.png)

According to the [terminfo.scr][ti], the default is `xterm-color` for my Terminal (in OS X). So, when I set that, instead of using `xterm-256color`, which I usually have. Then it draws everything correct, but instead the cursor is visible/blinking.

![2048](https://user-images.githubusercontent.com/3958664/52407924-dc0ece00-2ad1-11e9-893b-ae46d7d50e8b.gif)

_…even though I've seen `curs_set(0)` is set in `setup_screen()`._

Do you have a fix/workaround for this?

After some searching I found a workaround to prepend the command with `TERM` when starting it. There are a few different ones working, like:

```bash
$ TERM=st 2048
$ TERM=nsterm 2048
```

Both works, and one could make an alias of it - but, it would be nice if it worked normally. As it always have. :)

[nc]: https://www.gnu.org/software/ncurses/
[ti]: https://invisible-island.net/ncurses/terminfo.src.html#toc-_X_T_E_R_M

**Comment by alewmoose** [comment]
I'll check, thanks!

**Comment by alewmoose** [comment]
I couldn't reproduce the case with missing vertical lines.

The only workaround for the cursor problem I found is setting the `TERM` environment variable to something different than `xterm*`, i.e. exactly what you do, but from the inside of the program using `setenv`.  Also, the cursor problem is not unique to the `2048-in-terminal`, it behaves the same in other ncurses programs too, for instance `cmus` and `mocp`.

I think it's better to leave things as is, and set the `TERM` variable if necessary the way you do it.

**Comment by iefdev** [comment]
Ah, ok… I'll go with the TERM-setting, for now.

Thanks! for looking at it. :+1:
